### PR TITLE
Make ParserResult publicly usable

### PR DESCRIPTION
**Pull request by buster**
One can't use ParseResult, because it's not public.

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks!

**Comment by untitaker** [comment]
@niax Should I make a new release because of this and #20?

**Comment by niax** [comment]
Depends, @buster do you have any other changes that you'd want before a new release is cut?

**Comment by buster** [comment]
Thanks you two.. No, so far, with 33°C and approaching the weekend, there will not be any input anymore :)

**Comment by untitaker** [comment]
:party: 0.0.12 is out.

**Pull request merged**
